import "@repo/ui/styles.css";
import "./globals.css";
import type { Metadata } from "next";
import { DM_Sans, Geist, Space_Mono } from "next/font/google";
import { ThemeProvider } from "../lib/providers/theme-provider";

const geist = Geist({ subsets: ["latin"] });

const dm_sans = DM_Sans({ subsets: ["latin"] });
const space_mono = Space_Mono({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={dm_sans.className + " " + space_mono.className}>
        <ThemeProvider
          attribute="class"
          enableSystem
          disableTransitionOnChange
          defaultTheme="dark"
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
